# Generated by Django 4.0.2 on 2022-03-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_events_title_alter_events_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='datetime',
        ),
    ]
