# Generated by Django 4.0.2 on 2022-03-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_date_events_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
