# Generated by Django 4.0.2 on 2022-03-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_attending'),
        ('events', '0006_rename_review_text_review_text_alter_review_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event_id',
        ),
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event'),
        ),
        migrations.AlterField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.userprofile'),
        ),
    ]
